# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: William Fu
title: Analytics Engineer
email: williamfuu@gmail.com
#website: fuwilliam.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: fuwilliam
#linkedin_username: jameswgrant
# Additional icon links
additional_links:
- title: PDF version
  icon: fas file-pdf
  url: https://fuwilliam.github.io/

# About Section
# about_title: About Me
about_profile_image: images/profile_.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey! I'm William (but I usually go by Fu) and I have about 5 years of experience working with data, more recently focusing in analytics engineering.
  
  I started off as the Excel guy, began delivering dashboards with various data viz tools, and then moved on to building ETL pipelines and delivering data models. With this baggage, I've been shifting towards learning SWE skills and best practices to become a better fit and keep up with the rapidly evolving fields of analytics and data engineering. 

  Overall, I find enjoyment in wrangling data into assets that facilitate access to reliable, actionable information.  

  I'm pretty confident with:   <mark>SQL</mark>, <mark>Python</mark>, <mark>Power BI/Tableau/Qlik</mark>, <mark>Data Modeling</mark>

  I'm fairly comfortable with:  <mark>Airflow</mark>, <mark>dbt</mark>, <mark>BigQuery/Athena</mark>, <mark>git</mark>

  I know the basics of:   <mark>Spark</mark>, <mark>Scala</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Battle Rap
        link: github.com/fuwilliam/battle-rap
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nubank
        link: nubank.com
        # link_text: boringcompany.com
        sub_title: Analytics Engineer
        caption: July 2021 - Apr 2022
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Federal University of Rio Grande do Sul (UFRGS)
        description: Industrial Engineering (BSc) 
      - layout: left
        sub_title: University of Wisconsin-Madison
        description: Industrial Engineering (1y exchange program)

  - title: Fun facts about William
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Owned by [two standard issue cats](https://imgur.com/a/V8NTC9r);
      - Mostly [listens to hip hop](https://open.spotify.com/playlist/6Lwab4nJQ8DpNm7LK8SVdP?si=806aada265b94e42) (hence the battle-rap project);
      - [Mechanical keyboard](https://i.imgur.com/lo8eQaa.jpg) enthusiast (also tech gadgets in general);
      - [Maxed](https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=Ekali) on Old School Runescape. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
