# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: William Fu
title: Analytics Engineer
email: williamfuu@gmail.com
#website: fuwilliam.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: fuwilliam
#linkedin_username: jameswgrant
# Additional icon links
additional_links:
- title: PDF resume
  icon: fas fa-file-pdf
  url: https://fuwilliam.github.io/

# About Section
# about_title: About Me
about_profile_image: images/profile_.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey! I'm William (but I usually go by my last name) and I have about 5 years of experience working with data, more recently focusing in analytics engineering. I find enjoyment in wrangling data into assets that facilitate access to reliable, actionable information!
  
  I started my career as an Excel guy, began constructing dashboards with various data viz tools, and then moved on to building ETL pipelines and delivering data models. With this baggage, I've been shifting towards learning SWE skills and best practices to keep up and become a better fit for the rapidly evolving fields of analytics and data engineering. 


  I'm pretty confident with:   <mark>SQL</mark>, <mark>Python</mark>, <mark>Power BI/Tableau/Qlik</mark>, <mark>Data Modeling</mark>

  I'm fairly comfortable with:  <mark>Airflow</mark>, <mark>dbt</mark>, <mark>BigQuery/Athena</mark>, <mark>git</mark>

  I know the basics of:   <mark>Spark</mark>, <mark>Scala</mark>, <mark>Docker</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Battle Rap
        link: fuwilliam.github.io/battle-rap
        additional_links:
          - title:  fuwilliam/battle-rap
            icon: fab fa-github
            url: github.com/fuwilliam/battle-rap
        quote: >
          A project built to answer the age-old question: who is the best rapper?
        description: | # this will include new lines to allow paragraphs
          This project was conceived through a combination of my fandom of hip-hop and my desire to
          learn and practice software and data engineering skills.

          A list of hip-hop / rap artists are compiled with certain criteria from the <mark>Spotify API</mark>.
          Through a web app, users are prompted to choose between two artists in a head-to-head matchup. 
          With the matchup results, <mark>Airflow</mark> then orchestrates loading the data to <mark>BigQuery</mark>, 
          followed by the transformation and documentation via <mark>dbt</mark>, which in turn 
          enables the analysis of metrics such as rapper win rate in a <mark>Power BI</mark> dashboard.

          Overall, building this project has helped me bridge the gap between my BI centered background 
          and the skillset of the modern analytics engineer, while hopefully settling some music related debates.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nubank
        border: weak
        link: nubank.com.br
        # link_text: boringcompany.com
        sub_title: Analytics Engineer
        caption: 07/2021 - 04/2022
        description: | # this will include new lines to allow paragraphs
            - Delivered xxx core datasets related to ...;

            - Mapped existing ecosystem of collections datasets and its dependencies;

            - Supported business analysts (...) understanding sources blablabla

            - Built multiple bespoke SQL tests ...;

            - Implemented unit testing xxx.

      - layout: left
        title: Sicredi
        border: weak
        link: https://www.sicredi.com.br/site/home-en/
        link_text: sicredi.com.br
        sub_title: Data Analyst II
        caption: 04/2020 - 07/2021
        description: | # this will include new lines to allow paragraphs

            - Worked in the migration of over 20 dashboards from Tableau and AWS
            Quicksight to Power BI, revamping data modeling / business metrics,
            and ensuring a smoother transition between tools;

            - Continuously supported the data analyst chapter with performance
            tuning in SQL queries, resulting in direct savings in AWS Athena;

            - Supported development of datasets by migrating business users'
            SQL queries into Spark Scala code;

            - Created a Power BI style guide, with best practices in development &
            data visualization and publishing a standardized report theme
            (color palette, company branding, fonts).

      - layout: left
        title: Portocred
        border: weak
        link: portocred.com.br
        # link_text: boringcompany.com
        sub_title: BI Analyst II
        caption: 08/2019 - 04/2020
        description: | # this will include new lines to allow paragraphs

            - Developed ETL pipeline for Salesforce Marketing Cloud data for CRM data analysis. 
            Implemented version control and automation of SSIS packages through BIML scripting;

            - Built CRM campaign performance dashboards in Power BI, creating cost
            effectiveness, conversion rate, NPS, amongst other KPIs;

            - Performed and enabled deep-dive analysis over CRM campaign
            performance, allowing for more efficient marketing efforts. Insights
            contributed to a 30% increase in click conversion rate YoY;

            - Implemented and communicated various best practices regarding query
            performance, data types and naming schemes within team’s SQL Server
            data warehouse.

      - layout: left
        title: DLL Group
        border: weak
        link: dllgroup.com
        # link_text: boringcompany.com
        sub_title: BI Analyst I
        caption: 01/2018 – 08/2019
        description: | # this will include new lines to allow paragraphs
            - Main reference in Qlik Sense development within the company - built
            Brazil’s KPI dashboard, which was popularized globally. Usage of
            advanced Set Analysis and Qlik scripting;

            - Created and conducted Qlik Sense training sessions for internal users;

            - Development and maintenance of SSIS pipelines, delivering key tables
            used for credit risk management to the data warehouse;

            - Member on the winning team of a global innovation competition.
            Created and presented a pitch to the company’s executive board.
            Awarded with EUR 125k to implement the idea.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Federal University of Rio Grande do Sul (UFRGS)
        description: Industrial Engineering (B.Sc.)
      - layout: left
        sub_title: University of Wisconsin-Madison
        description: Industrial Engineering (Exchange program)

  - title: Miscellaneous
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Proudly owned by [two standard issue cats](https://imgur.com/a/V8NTC9r) - see [/r/StandardIssueCat](reddit.com/r/StandardIssueCat);
      - Mostly [listen to hip hop](https://open.spotify.com/playlist/6Lwab4nJQ8DpNm7LK8SVdP?si=806aada265b94e42) (hence the battle-rap project);
      - [Mechanical keyboard](https://i.imgur.com/lo8eQaa.jpg) enthusiast (also tech gadgets in general);
      - [Maxed](https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=Ekali) on Old School Runescape. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
